### ISSUE TITLE
tsc error due to passing paths in the commandline on all the exercises

### ISSUE THREAD

**Issue by aditya211935** [total-typescript/advanced-patterns-workshop#6]
`error TS6064: Option 'paths' can only be specified in 'tsconfig.json' file or set to 'null' on command line.` is returned in "Checking types..."

This is due to `paths` being specified in tsconfig.json and the cli parsing the tsconfig.json file and converting it into commandline arguments. However, `paths` can't be converted hence the error.

**Comment by aditya211935** [comment]
@mattpocock

**Comment by mattpocock** [comment]
@aditya211935 Thanks for the report! Fixed this upstream. It now creates a temporary tsconfig.json file while running the tests to get around the paths issue.
