### ISSUE TITLE
Excercises broken

### ISSUE THREAD

**Issue by freiondrej-lokalise** [total-typescript/advanced-patterns-workshop#9]
Hello,

I just started getting this error in excercises:

![image](https://github.com/total-typescript/advanced-patterns-workshop/assets/109138267/ebcb212d-4c92-4df2-bddd-66991dec1d8a)

**Comment by freiondrej-lokalise** [comment]
They started to work again now :) if you did something, thank you for a super quick update! 🙇

**Comment by mattpocock** [comment]
Probably a Stackblitz issue!
